### PR TITLE
chore: Remove obsolete dependency-matrix directory

### LINKED ISSUE #1089: Remove dependency-matrix
I don't see really a big value in this matrix as it stands now. I suggest to remove it.

### PR DESCRIPTION
**Pull request by hferentschik**
fixes #1089

### CODE REVIEW

**Comment by hferentschik** [comment]
@abayer - do you see any value in this dependency matrix? If we are going to remove it, is there anything else we have to take care off (aka update bot or whatever creates updates to this)?

**Comment by abayer** [comment]
Flaky tests are getting...annoying.

**Pull request merged**
