### PR TITLE
fix: bump lighthouse image tag in chart

### PR DESCRIPTION
**Pull request by wbrefvem**
Addresses #94

### CODE REVIEW

**Comment by jstrachan** [comment]
the image tag is already updated as part of the release pipeline:
https://github.com/jenkins-x/lighthouse/blob/v0.0.65/charts/lighthouse/values.yaml#L15

**Comment by wbrefvem** [comment]
@jstrachan Okay so this is something I didn't understand until just now. I get that polluting master with a new commit every time the version bumps is not ideal, but the way things now work we 1) leave master to languish with an old version, and 2) don't properly tag master with each release. Both make developing worse, the latter because local git tooling (not just the git cli, but shell integration as well) is a lot nicer when you can see all of the tags in master's `git log`.

**Comment by jstrachan** [comment]
we usually use `latest` in master - how about using that in the master branch and getting the pipeline to also tag each release image with `latest`?

I don't follow the tag comment though - everything's tagged here just fine: https://github.com/jenkins-x/lighthouse/releases e.g. https://github.com/jenkins-x/lighthouse/tree/v0.0.65

**Pull request merged**
