### PR TITLE
feat: add support to set git local repository directory for webhook

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
hi @jstrachan, would you mind helping me to review this PR? Sorry to address you directly. I don't' know if we have a GitHub team to address.

**Comment by jstrachan** [comment]
I didn't quite grok this PR - is it to enable git cache dir for the git client? I wonder if we should split out that "add-owner" plugin into a separate PR as I"m not sure what that does yet

**Comment by LinuxSuRen** [comment]
> I didn't quite grok this PR - is it to enable git cache dir for the git client? I wonder if we should split out that "add-owner" plugin into a separate PR as I"m not sure what that does yet

I already be care about this part. I didn't mean to commit them.

**Comment by LinuxSuRen** [comment]
Any updates here?

**Comment by tomhobson** [comment]
Hey @LinuxSuRen, is this still something you'd like looking at?

**Comment by LinuxSuRen** [comment]
> Hey @LinuxSuRen, is this still something you'd like looking at?

I still believe this is a good to have feature.

**Review by tomhobson — CHANGES_REQUESTED** [review]
Can we get some basic tests for this?

We're trying to have a push on testing and it also would help others to understand this feature if it has some relevant unit tests (as I'm currently struggling to work out how this is defaulted otherwise)

**Comment by msvticket** [comment]
This PR is abandoned by the submitter

**Pull request closed without merging**
