### PR TITLE
only Issue owner and Issue Assignee can label hold

### PR DESCRIPTION
**Pull request by joker00777**
To not allow everyone to use hold label only the pr owner and the pr assignee can use them.

### CODE REVIEW

**Comment by joker00777** [comment]
@ankitm123 just wanted to take your ideas if this looks cool than i will write the test case : )

**Comment by ankitm123** [comment]
Not sure abt this, I think we want to allow all members of an org to be able to add/remove hold.

**Comment by joker00777** [comment]
okai 
so should  i close it ?

**Pull request closed without merging**
