### PR TITLE
refactor: milestone plugin

### PR DESCRIPTION
**Pull request by eddycharly**
This PR refactors the milestone plugin.

The `Milestone` service doesn't exist in `go-scm` though, not sure if this plugin works ?

### CODE REVIEW

**Comment by hferentschik** [comment]
> The Milestone service doesn't exist in go-scm though, not sure if this plugin works ?

If it does not work, I'd rather remove this altogether? @abayer wdyt?

**Comment by abayer** [comment]
I'd lean towards actually implementing milestones (in GitHub and Gitea, epics in GitLab) in go-scm. I might do that today.

**Comment by hferentschik** [comment]
> I'd lean towards actually implementing milestones in go-scm. I might do that today.

so it is a concept available across scm providers? Fair enough.

**Comment by abayer** [comment]
/lgtm

I'll get a PR up later today for the milestone API and related stuff in go-scm, and then a followup to actually implement it here.

**Comment by eddycharly** [comment]
I’m thinking about adding providers exclusion for plugins. It could be handy if the api is not available with every provider.

**Pull request merged**
