### PR TITLE
chore: make webhook event handlers private

### PR DESCRIPTION
**Pull request by eddycharly**
This PR makes webhook event handlers private (they don't need to be public)

### CODE REVIEW

**Comment by abayer** [comment]
/lgtm

I wonder why they were public in the first place...

**Comment by eddycharly** [comment]
Yeah, it looked strange to have these functions public, it's an implementation detail by nature.

**Comment by eddycharly** [comment]
It would be nice to remove the legacy_helpers too. It itches me =)

**Pull request merged**
