### PR TITLE
feat: generate CRDs from types

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds CRDs generation from types in `pkg/apis/lighthouse/v1alpha1`.

This adds CRD schema documentation.

### CODE REVIEW

**Comment by abayer** [comment]
oooo, interesting. We should probably change `make generate-client` to just `make generate` and have it depend on `codegen-clientset` and `crd-manifests` targets...

**Comment by eddycharly** [comment]
Yep but u believe it exits with code 1 because of some structs in tekton don't have the json tag...

**Comment by abayer** [comment]
`tekton` failure:

```
 helm3 install -f myvalues.yaml --namespace lh-test lighthouse charts/lighthouse
Error: CustomResourceDefinition.apiextensions.k8s.io "lighthousejobs.lighthouse.jenkins.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[params].items.properties[value].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[tasks].items.properties[taskSpec].properties[params].items.properties[default].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[tasks].items.properties[conditions].items.properties[params].items.properties[value].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[tasks].items.properties[params].items.properties[value].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[finally].items.properties[taskSpec].properties[params].items.properties[default].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[finally].items.properties[conditions].items.properties[params].items.properties[value].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[finally].items.properties[params].items.properties[value].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[spec].properties[pipeline_run_spec].properties[pipelineSpec].properties[params].items.properties[default].type: Unsupported value: "Any": supported values: "array", "boolean", "integer", "number", "object", "string", spec.validation.openAPIV3Schema.properties[status].properties[activity].properties[stages].items.properties[stages].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[status].properties[activity].properties[stages].items.properties[steps].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[status].properties[activity].properties[steps].items.properties[stages].items.type: Required value: must not be empty for specified array items, spec.validation.openAPIV3Schema.properties[status].properties[activity].properties[steps].items.properties[steps].items.type: Required value: must not be empty for specified array items]
```

**Comment by eddycharly** [comment]
ah thanks, i can test it locally now

**Pull request merged**
