### PR TITLE
fix: the OWNERS file use the number username

### PR DESCRIPTION
**Pull request by rubinus**
while OWNERS file has number , yaml unmarshal is err ,but simple.Empty() return true

### CODE REVIEW

**Comment by rubinus** [comment]
// case one: if github username type is number,for example 23456346,not string, the err as below：
	    // unmarshaling JSON: while decoding JSON: json: cannot unmarshal number into
	    // Go struct field SimpleConfig.approvers of type string
	    // if OWNER files content
	    // approvers:
	    //   - rubinus
	    //   - 23456346
	    // reviewers:
	    //   - rubinus
	    //   - 23456346
	    // but result can be as below，the simple.Empty() not false
      // simple.Config.Approvers = [rubinus]
      // simple.Config.Reviewers = [rubinus]
	    // the number github username is lost，but the approvers and reviewers have value
	    // the another solution: you ensure OWNERS file use "23456346" replace 23456346
	    // other words: OWNERS file use the all string username

**Comment by rawlingsj** [comment]
got a test failure:
```


time="2022-01-11T10:47:51Z" level=warning msg="AND OWNERS IS: &{RepoAliases:map[best-approvers:map[blahonga:{} carl:{} cjwagner:{}] best-reviewers:map[bob:{} carl:{}]] approvers:map[] reviewers:map[] requiredReviewers:map[] labels:map[] options:map[] baseDir:/tmp/git414810866 enableMDYAML:true dirExcludes:map[.git:{} _output:{}] log:0xc00010c690}" client=repoowners
--
  |   |   |   | --- FAIL: TestOwnersRegexpFiltering (0.53s)
  |   |   |   | helpers.go:29: using default branch: master
  |   |   |   | helpers.go:29: using default branch: master
  |   |   |   | repoowners_test.go:309: labels: map[string]map[*regexp.Regexp]sets.String{}
  |   |   |   |  
  |   |   |   | repoowners_test.go:312: For file "re/a/go.go" expected labels ["re/all" "re/go" "re/go-in-a"], but got [].
  |   |   |   | repoowners_test.go:312: For file "re/a/md.md" expected labels ["re/all" "re/md-in-a"], but got [].
  |   |   |   | repoowners_test.go:312: For file "re/a/txt.txt" expected labels ["re/all"], but got [].
  |   |   |   | repoowners_test.go:312: For file "re/go.go" expected labels ["re/all" "re/go"], but got [].
  |   |   |   | repoowners_test.go:312: For file "re/txt.txt" expected labels ["re/all"], but got [].
  |   |   |   | repoowners_test.go:312: For file "re/b/md.md" expected labels ["re/all"], but got [].
```

**Comment by ankitm123** [comment]
/hold
can we add a test case for this? Test suites already exist for lighthouse.

**Comment by rubinus** [comment]
@ankitm123 what does next follow?

**Comment by ankitm123** [comment]
> @ankitm123 what does next follow?

Not sure, what u mean, but will be good to look at the failing tests ... let me know if u need some help, I can take a look.

**Comment by msvticket** [comment]
The PR has been abandoned by the submitter

**Pull request closed without merging**
