### PR TITLE
feat: upgrade tekton 0.41.0

### PR DESCRIPTION
**Pull request by tomhobson**

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
Can not check what happen for CI failed, it need to login :(

**Comment by msvticket** [comment]
> Can not check what happen for CI failed, it need to login :(

Maybe you found out by yourself, but it does fail in `make test`:

```
 	--- FAIL: TestLoadPipelineRunTest (0.67s)
		    load_pipelinerun_test.go:115: test pipeline-missing-refs-fails generated expected error failed to load Task refs for in repo myorg/ with sha : failed to find path test_data/load_pipelinerun/pipeline-missing-refs-fails/git-clone.yaml in PipelineSpec: failed to read file test_data/load_pipelinerun/pipeline-missing-refs-fails/git-clone.yaml: open test_data/load_pipelinerun/pipeline-missing-refs-fails/git-clone.yaml: no such file or directory
		panic: runtime error: invalid memory address or nil pointer dereference [recovered]
			panic: runtime error: invalid memory address or nil pointer dereference
		[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x13fa638]
		
		goroutine 12 [running]:
		testing.tRunner.func1.2({0x153ed00, 0x244dda0})
			/usr/local/go/src/testing/testing.go:1396 +0x24e
		testing.tRunner.func1()
			/usr/local/go/src/testing/testing.go:1399 +0x39f
		panic({0x153ed00, 0x244dda0})
			/usr/local/go/src/runtime/panic.go:884 +0x212
		github.com/jenkins-x/lighthouse/pkg/triggerconfig/inrepo.LoadTektonResourceAsPipelineRun(0xc000591ee0, {0xc0004ea700, 0x62d, 0x62e})
			/workspace/source/pkg/triggerconfig/inrepo/load_pipelinerun.go:125 +0xab8
		github.com/jenkins-x/lighthouse/pkg/triggerconfig/inrepo.TestLoadPipelineRunTest(0xc0000d5380)
			/workspace/source/pkg/triggerconfig/inrepo/load_pipelinerun_test.go:111 +0xa72
		testing.tRunner(0xc0000d5380, 0x17f2748)
			/usr/local/go/src/testing/testing.go:1446 +0x10b
		created by testing.(*T).Run
			/usr/local/go/src/testing/testing.go:1493 +0x35f
		FAIL	github.com/jenkins-x/lighthouse/pkg/triggerconfig/inrepo	0.773s
```

**Comment by tomhobson** [comment]
/hold

this is a big change and requires some more testing and some pipeline catalog updates (we think we're going to build a migrator!)

**Comment by tomhobson** [comment]
It's acension day in Sweden so @msvticket isn't around and I guess @babadofar  isn't either.
We only have limited time to get this working so I'm approving this by myself as a one off. It won't merge into jx3 versions as tekton 0.41.0 is required before that can happen.
/approve

I'll discuss with the team and revert if required, but there's going to be no impact for now as it's not going into jx3 versions as I said before.

**Pull request merged**
