### PR TITLE
chore: make e2e tests non sensible to the ingress name

### PR DESCRIPTION
**Pull request by eddycharly**
This PR makes e2e tests non sensible to the ingress name.

The ingress is looked up by labels rather than by name.

### CODE REVIEW

**Comment by eddycharly** [comment]
There might be something wrong...

**Comment by eddycharly** [comment]
The jsonpath expression was wrong.

**Comment by abayer** [comment]
/hold

Holding briefly for getting a jx PR downstream of Lighthouse to actually merge. Will unhold soon.

**Pull request merged**
