### PR TITLE
chore: remove most of Plank config

### PR DESCRIPTION
**Pull request by eddycharly**
This PR removes JenkinsOperator and most of Plank config.

### CODE REVIEW

**Comment by abayer** [comment]
Let's keep the Jenkins stuff - since I'd really like to get Jenkins support in here (see #885) and we may want to keep a fair amount of the same configuration.

**Comment by eddycharly** [comment]
Done

**Comment by eddycharly** [comment]
How about Gerrit ? You want to keep it around ?

**Comment by abayer** [comment]
Nah, Gerrit can go away. =)

**Comment by eddycharly** [comment]
Ok, forgot to rebuild docs...

**Pull request merged**
