### PR TITLE
chore: Improve chart notes

### PR DESCRIPTION
**Pull request by eddycharly**
This PR improves chart NOTES.TXT.

### CODE REVIEW

**Comment by eddycharly** [comment]
Dunno what failed, how can i access the build logs ?

**Comment by hferentschik** [comment]
> Dunno what failed, how can i access the build logs ?

Looks like an infrastructure issue:

```
curl --fail -u *****:************ -X DELETE http://jenkins-x-chartmuseum:8080/api/charts/lighthouse/0.0.0-SNAPSHOT-PR-909-1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed connect to jenkins-x-chartmuseum:8080; Connection refused
make: *** [delete-from-chartmuseum] Error 7
```

**Comment by eddycharly** [comment]
Thanks, i'll give it another try then.

/retest

**Pull request merged**
