### PR TITLE
chore: Remove golint and blunderbuss plugins config (dead code)

### PR DESCRIPTION
**Pull request by eddycharly**
This PR removes `golint` and `blunderbuss` plugins config as they are not used in the code.

### CODE REVIEW

**Comment by abayer** [comment]
I actually started trying to port the golint plugin over recently but got stuck figuring out how to deal with the line by line comments in a way that would work with GitLab and BitBucket Server. I’ll probably come back to it at some point, but I don’t see a problem in removing the config for now. The only concern I could have would be that existing Prow configs still need to be valid, but I believe it’ll just ignore unknown fields when unmarshaling anyway.

**Comment by abayer** [comment]
A unit test failed in `pkg/repoconfig/merge`

**Comment by eddycharly** [comment]
As I’m writing plugins docs I started cleaning up the package at the same time. 

I’ll look at the failing test tonight or tomorrow.

**Pull request merged**
