### PR TITLE
chore: Stop creating update PRs on jx.git on release

### PR DESCRIPTION
**Pull request by abayer**
No one's actually merging them, so let's stop bothering to create them.

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

**Comment by abayer** [comment]
Just added a new commit adding @eddycharly to `OWNERS` as well. =)

/assign @hferentschik

**Comment by eddycharly** [comment]
Thank you @abayer 

/lgtm

**Pull request merged**
