### PR TITLE
feat: Tests/official support for Gitea

### PR DESCRIPTION
**Pull request by abayer**
Yay! Gitea 1.13 finally released, so this is ready to go. =)

### CODE REVIEW

**Comment by abayer** [comment]
I'm using the `tekton` context for the moment.

**Comment by abayer** [comment]
Blech, there seems to be a problem with getting the token set properly in the Gitea client under the hood. Working on it.

**Comment by abayer** [comment]
So current situation is that it's not populating the `OWNERS` link from `Needs approval from an approver in each of these files` in the initial comment, and that means I have to wade into the hell of owners file parsing and such. yay. =)

**Comment by abayer** [comment]
OK! So the problem is that we have to have a hack to do the `PullRequest.ListChanges` function with Gitea, because they don't have an equivalent endpoint. So what I decided to do was get the `.patch` and parse that into the changes we need. Hoorah! Should work! But https://github.com/go-gitea/gitea/issues/10923 - can't get the `.diff` or `.patch` with an api token, just via basic authentication. Except! https://github.com/go-gitea/gitea/pull/11751 - it's fixed, now there are such endpoints...but they aren't released yet. We need to wait for 1.13.0. Baaaaah.

**Comment by abayer** [comment]
I hacked around it by using the latest pre-release image of gitea, but we aren't going to want to merge this until it's actually released. I also opened https://gitea.com/gitea/go-sdk/pulls/398 so we don't have to do hacks for `ListChanges`. Next up is figuring out why Keeper refuses to start...

**Comment by abayer** [comment]
yaaaaaay everything passed.

**Comment by abayer** [comment]
So this works - it's just waiting on Gitea 1.13.0 releasing for the `.patch` endpoint (so we can calculate the list of changed files in a PR). I'll keep it on WIP until then.

**Comment by eddycharly** [comment]
DeleteRef was not implemented for Gitea, the branchcleaner plugin does not work. I opened a PR (https://github.com/jenkins-x/go-scm/pull/177)

**Comment by eddycharly** [comment]
@abayer any idea how to take care of the branch name when deleting a branch in the branchcleaner plugin ?
https://github.com/jenkins-x/lighthouse/blob/5fd1d1f5e64ec136ed18591181f1e863e0667cca/pkg/plugins/branchcleaner/branchcleaner.go#L63

Adding the `heads/` prefix does not work for gitea.

**Comment by abayer** [comment]
Hrm, I'll take a look. I'm actually kinda regretting using the Gitea Go SDK behind the scenes now because it doesn't work the way the other providers do re: pagination, so I may just rewrite everything today. =)

**Comment by eddycharly** [comment]
Yeah, in kloops i introduced an `ScmTools` interface to accommodate for these differences (https://github.com/eddycharly/kloops/blob/520d6dc1e92a1be8979e082c47ba908ebb31623a/pkg/scmprovider/tools.go#L22-L27).

**Comment by abayer** [comment]
Let's see how far I get with rewriting - if I don't get it done before Gitea 1.13 is released, we can special case like you're doing in kloops.

**Comment by abayer** [comment]
Ah-ha, the new version of gitea/go-sdk has `http.Response` (well, a wrapper around it, but...) returns now, so tada, https://github.com/jenkins-x/go-scm/pull/180

**Comment by hferentschik** [comment]
@abayer what's the state on this one? I guess at the very least is seems to require a rebase.

**Comment by abayer** [comment]
@hferentschik Waiting for gitea to release 1.13 for https://github.com/go-gitea/gitea/pull/11751, which we’re currently using to construct the list of changed files in a PR.

**Comment by abayer** [comment]
Well, blech, the Gitea chart is currently broken on k8s 1.18 - https://gitea.com/gitea/helm-chart/issues/77.

**Pull request merged**
