### PR TITLE
refactor: update go version to 1.18.4

### PR DESCRIPTION
**Pull request by sshiv5768**
Related to https://github.com/jenkins-x/jx/issues/8283

### CODE REVIEW

**Comment by ankitm123** [comment]
No changes after running go mod tidy?

**Comment by sshiv5768** [comment]
I changed Golang version in it from ``1.17`` to ``1.18`` in go.mod

**Comment by ankitm123** [comment]
Run go mod tidy after changing the version in the go.mod file, this will ensure the go.mod and go.sum files are updated. See: https://jenkins-x.io/community/maintainer_guide/go-upgrades/

**Comment by sshiv5768** [comment]
@ankitm123 I got 2 errors while running ``go mod tidy`` 

1: go: github.com/gogo/protobuf@v1.2.2-0.20190723190241-65acae22fc9d: git -c protocol.version=0 fetch --unshallow -f https://github.com/gogo/protobuf refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/shivlalsharma/go/pkg/mod/cache/vcs/008745bab24c72f9836ba820e1058a38f5f3bf297e848d8fddb723e5eaefb30a: exit status 128:
	fatal: the remote end hung up unexpectedly
	fatal: early EOF
	fatal: index-pack failed

2: go: github.com/garyburd/redigo@v0.0.0-20150301180006-535138d7bcd7: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/shivlalsharma/go/pkg/mod/cache/vcs/ac29ab50a4fbaf6da97387824411aaa95a5364a02f9398964da7b5ad27006c30: exit status 128:
	fatal: unable to access 'https://github.com/garyburd/redigo/': Could not resolve host: github.com

these twos.

**Comment by ankitm123** [comment]
did u re-run them again? seems like a network issue to me ...

**Comment by rajatgupta24** [comment]
Hello @sshiv5768, @ankitm123,
I also tried to update this repo, 
- I first updated the go-version to 1.18 in go.mod
- then run `go mod tidy`, no errors in my case
- then `make build`, also completed successfully (but -i is depreacted)
- then `make test`, shows some test failed.

image

**Pull request closed without merging**
