### PR TITLE
fix: handle case when master or new PR don't have jx config

### PR DESCRIPTION
**Pull request by yelhouti**
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>

### CODE REVIEW

**Comment by jstrachan** [comment]
@yelhouti any chance you can run `make fmt` on your PR? getting a lint failure...

```
diff --git a/pkg/triggerconfig/inrepo/calculate.go b/pkg/triggerconfig/inrepo/calculate.go
index 347f45d..d3c7509 100644
--- a/pkg/triggerconfig/inrepo/calculate.go
+++ b/pkg/triggerconfig/inrepo/calculate.go
@@ -1,9 +1,10 @@
 package inrepo
 
 import (
-	"github.com/jenkins-x/lighthouse/pkg/triggerconfig/merge"
 	"strings"
 
+	"github.com/jenkins-x/lighthouse/pkg/triggerconfig/merge"
+
 	"github.com/jenkins-x/go-scm/scm"
 	"github.com/jenkins-x/lighthouse/pkg/config"
 	"github.com/jenkins-x/lighthouse/pkg/plugins"
```

**Comment by yelhouti** [comment]
my bad fixed

**Pull request merged**
