### PR TITLE
refactor: rework jobs config

### PR DESCRIPTION
**Pull request by eddycharly**
This PR moves all job related config into its own package.

This is work in progress, i feel like there some improvements that can be done around initialization/validation.

Related issue #965

### CODE REVIEW

**Comment by abayer** [comment]
fwiw, lint failures:
```
pkg/config/job/base.go:25:6: type name will be used as job.JobBase by other packages, and that stutters; consider calling this Base
pkg/config/job/brancher.go:45:1: exported method Brancher.SetBrancherRegexes should have comment or be unexported
pkg/config/job/regexpchangematcher.go:61:1: exported method RegexpChangeMatcher.SetChangeRegexes should have comment or be unexported
```

**Comment by eddycharly** [comment]
Yeah, I didn’t focus on linting yet.
Moving code around, fixing tests, identifying some strange constructs that I would like to implement differently...

**Comment by eddycharly** [comment]
I was thinking about using dot imports but not sure if it’s good practice or not...

**Comment by eddycharly** [comment]
It should be ready for review. There are probably a few things that could be improved but most of the work has been done.

I will continue with lighthouse config related concern now.

**Pull request merged**
