### PR TITLE
docs: Update plugins.yaml to add trigger plugin

### PR DESCRIPTION
**Pull request by zxDiscovery**
This PR adds trigger plugins in doc.
see https://github.com/zxDiscovery/lighthouse/blob/master/docs/INSTALL.md

### CODE REVIEW

**Comment by eddycharly** [comment]
Thanks !

Please rename your PR to `docs: Update plugins.yaml for add trigger plugin`, it has to follow the semantic commit message rule (https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716).

/lgtm

**Comment by zxDiscovery** [comment]
@eddycharly  I have already updated the PR name but semantic still failed. What should I do for this?

**Comment by eddycharly** [comment]
You probably have to amend your commit too.

**Comment by zxDiscovery** [comment]
@eddycharly Thanks. Semantic passed. I need another label.

**Pull request merged**
