### PR TITLE
fix: use assign PR in plugins when working with PR instead of assign issue

### PR DESCRIPTION
**Pull request by yelhouti**

### CODE REVIEW

**Comment by jstrachan** [comment]
@yelhouti looks like `make vet` fails...
```
vet: pkg/plugins/assign/assign_test.go:428:75: cannot use fc (variable of type *fakeClient) as scmProviderClient value in argument to newAssignHandler: missing method AssignPR
```

**Comment by yelhouti** [comment]
last test failing is because of:
https://github.com/jenkins-x/go-scm/pull/203
please merge this and rebase my PR for this test to pass

**Pull request merged**
