### PR TITLE
feat: update cronjob version for lighthouse

### PR DESCRIPTION
**Pull request by tomhobson**
Going to go through the jenkins-x objects to get them ready for an upgrade

```
NAME                                                              KIND                      VERSION               REPLACEMENT      REMOVED   DEPRECATED   REPL AVAIL
lighthouse-gc-jobs                                                CronJob                   batch/v1beta1         batch/v1         false     true         true

### CODE REVIEW

**Comment by babadofar** [comment]
https://github.com/jenkins-x/jx/issues/8454

**Review by davidrmcgee — COMMENTED** [review]
If lighthouse is committed to support v1.25 of Kubernetes, then this change is required.

**Comment by tomhobson** [comment]
> If lighthouse is committed to support v1.25 of Kubernetes, then this change is required.

@davidrmcgee hey, I closed this as it was done in another PR. The latest version of lighthouse should support this now :) 

https://github.com/jenkins-x/lighthouse/blob/main/charts/lighthouse/templates/gc-jobs-cj.yaml

**Pull request closed without merging**
